sudo: false
language: node_js
cache: yarn
before_install: yarn global add codecov
after_success:
  - yarn nyc report --reporter=text-lcov > coverage.lcov
  - codecov
notifications:
  email: false
node_js:
  - 'stable'
  - 'lts/*'
